# Nginx entrypoint
nginx:
    image: nginx:1.9
    volumes_from:
        - web
    links:
        - web
    ports:
        - "8000:80"
# PHP-FPM service
web:
  build: ./
  volumes:
    - ./drupal:/var/www/html
    - ./config/nginx-docker.conf:/etc/nginx/conf.d/default.conf
  links:
    - mysql:mysql
    - solr:solr
  working_dir: /var/www/html
  expose:
    - "9000"
# MySQL Server
mysql:
  image: mysql:5.7
  environment:
    MYSQL_USER: drupal
    MYSQL_PASSWORD: drupal
    MYSQL_DATABASE: drupal
    MYSQL_ROOT_PASSWORD: ''
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  expose:
    - "3306"
# (Optional) Solr Server
solr:
  build: ../build/apachesolr-drupal-docker/4.x
  ports:
    - "8983:8983"
  expose:
    - "8983"
